extract_features:
  mini_batch_kmeans:
    n_clusters: 30
    n_init: 10
    random_state: 42
  ewma:
    alpha: 0.4

train:
  model_name: GRU
  units: 128
  learning_rate: 0.00010880878298250268
  batch_size: 64
  epochs: 100